version: '3.1'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: jwtdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mysql-data:/var/lib/mysql
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq-container"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672" # RabbitMQ Management UI port
    networks:
      - my-network
volumes:
  mysql-data:
networks:
  my-network:
    driver: bridge